# name: Build Android

# on:
#   workflow_dispatch:

# jobs:
#   build:
#     name: Build APK
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout source
#         uses: actions/checkout@v2

#       - name: Setup java
#         uses: actions/setup-java@v3
#         with:
#           distribution: "temurin"
#           java-version: "17"

#       - name: Setup Android SDK
#         uses: android-actions/setup-android@v2

#       - name: Setup Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: 16.x

#       - name: Install Ionic
#         run: npm install -g @ionic/cli

#       - name: Install app dependencies
#         run: npm install

#       - name: Build Ionic App
#         run: ionic build

#       - name: Copy Android
#         run: ionic capacitor copy android

#       - name: Build Android Dev APK
#         run: ionic capacitor build android

#       - name: Build Android Release APK
#         run: ionic capacitor build android --release --prod

#       - name: Generate the Android App Bundle
#         working-directory: ./android/
#         run: ./gradlew bundle

#       - name: Upload dev APK
#         uses: actions/upload-artifact@v1
#         with:
#           name: app-dev
#           path: apk/app-debug.apk

#       - name: Upload release bundle
#         uses: actions/upload-artifact@v1
#         with:
#           name: app-release
#           path: apk/app.aab
name: Build Android

on:
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "11"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install Ionic
        run: npm install -g @ionic/cli

      - name: Install app dependencies
        run: npm install

      - name: Build Ionic App
        run: ionic build

      - name: Copy Android
        run: ionic capacitor copy android

      - name: Build Android Dev APK
        run: ionic capacitor build android --no-open

      # - name: Build Android Release APK
      #   run: ionic capacitor build android --no-open --release --prod

      - name: Generate the Android App Bundle
        working-directory: ./android/
        run: chmod +x gradlew && ./gradlew assembleDebug
      # - name: Generate the Android App Bundle
      #   working-directory: ./android/
      #   run: ./gradlew bundle

      - name: Upload dev APK
        uses: actions/upload-artifact@v1
        run: dir
        with:
          name: app-dev
          path: build/outputs/apk/app-debug.apk

      - name: Upload release bundle
        uses: actions/upload-artifact@v1
        with:
          name: app-release
          path: build/outputs/apk/app.aab
