name: "Run Tests on Master"

on:
  push:
  pull_request:
    branches:
      - "master"

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: install chrome headless
        run: sudo apt-get
      - name: Run Tests
        run: npm run test-github
